//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.EshheLegche
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Рацион.
    /// </summary>
    // *** Start programmer edit section *** (Рацион CustomAttributes)

    // *** End programmer edit section *** (Рацион CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РационE", new string[] {
            "НомерРациона as \'Номер рациона\'",
            "ТипКорма as \'Тип корма\'",
            "СоставКорма as \'Состав корма\'",
            "ВесКорма as \'Вес корма\'",
            "Сотрудники as \'Сотрудники\'",
            "Сотрудники.Фамилия as \'Фамилия\'"}, Hidden=new string[] {
            "Сотрудники.Фамилия"})]
    [MasterViewDefineAttribute("РационE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Фамилия")]
    [View("РационL", new string[] {
            "НомерРациона as \'Номер рациона\'",
            "ТипКорма as \'Тип корма\'",
            "СоставКорма as \'Состав корма\'",
            "ВесКорма as \'Вес корма\'",
            "Сотрудники.Фамилия as \'Фамилия\'"})]
    public class Рацион : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерРациона;
        
        private IIS.EshheLegche.ТипКорма fТипКорма;
        
        private string fСоставКорма;
        
        private string fВесКорма;
        
        private IIS.EshheLegche.Сотрудники fСотрудники;
        
        // *** Start programmer edit section *** (Рацион CustomMembers)

        // *** End programmer edit section *** (Рацион CustomMembers)

        
        /// <summary>
        /// ВесКорма.
        /// </summary>
        // *** Start programmer edit section *** (Рацион.ВесКорма CustomAttributes)

        // *** End programmer edit section *** (Рацион.ВесКорма CustomAttributes)
        [StrLen(255)]
        public virtual string ВесКорма
        {
            get
            {
                // *** Start programmer edit section *** (Рацион.ВесКорма Get start)

                // *** End programmer edit section *** (Рацион.ВесКорма Get start)
                string result = this.fВесКорма;
                // *** Start programmer edit section *** (Рацион.ВесКорма Get end)

                // *** End programmer edit section *** (Рацион.ВесКорма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Рацион.ВесКорма Set start)

                // *** End programmer edit section *** (Рацион.ВесКорма Set start)
                this.fВесКорма = value;
                // *** Start programmer edit section *** (Рацион.ВесКорма Set end)

                // *** End programmer edit section *** (Рацион.ВесКорма Set end)
            }
        }
        
        /// <summary>
        /// НомерРациона.
        /// </summary>
        // *** Start programmer edit section *** (Рацион.НомерРациона CustomAttributes)

        // *** End programmer edit section *** (Рацион.НомерРациона CustomAttributes)
        public virtual int НомерРациона
        {
            get
            {
                // *** Start programmer edit section *** (Рацион.НомерРациона Get start)

                // *** End programmer edit section *** (Рацион.НомерРациона Get start)
                int result = this.fНомерРациона;
                // *** Start programmer edit section *** (Рацион.НомерРациона Get end)

                // *** End programmer edit section *** (Рацион.НомерРациона Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Рацион.НомерРациона Set start)

                // *** End programmer edit section *** (Рацион.НомерРациона Set start)
                this.fНомерРациона = value;
                // *** Start programmer edit section *** (Рацион.НомерРациона Set end)

                // *** End programmer edit section *** (Рацион.НомерРациона Set end)
            }
        }
        
        /// <summary>
        /// СоставКорма.
        /// </summary>
        // *** Start programmer edit section *** (Рацион.СоставКорма CustomAttributes)

        // *** End programmer edit section *** (Рацион.СоставКорма CustomAttributes)
        [StrLen(255)]
        public virtual string СоставКорма
        {
            get
            {
                // *** Start programmer edit section *** (Рацион.СоставКорма Get start)

                // *** End programmer edit section *** (Рацион.СоставКорма Get start)
                string result = this.fСоставКорма;
                // *** Start programmer edit section *** (Рацион.СоставКорма Get end)

                // *** End programmer edit section *** (Рацион.СоставКорма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Рацион.СоставКорма Set start)

                // *** End programmer edit section *** (Рацион.СоставКорма Set start)
                this.fСоставКорма = value;
                // *** Start programmer edit section *** (Рацион.СоставКорма Set end)

                // *** End programmer edit section *** (Рацион.СоставКорма Set end)
            }
        }
        
        /// <summary>
        /// ТипКорма.
        /// </summary>
        // *** Start programmer edit section *** (Рацион.ТипКорма CustomAttributes)

        // *** End programmer edit section *** (Рацион.ТипКорма CustomAttributes)
        public virtual IIS.EshheLegche.ТипКорма ТипКорма
        {
            get
            {
                // *** Start programmer edit section *** (Рацион.ТипКорма Get start)

                // *** End programmer edit section *** (Рацион.ТипКорма Get start)
                IIS.EshheLegche.ТипКорма result = this.fТипКорма;
                // *** Start programmer edit section *** (Рацион.ТипКорма Get end)

                // *** End programmer edit section *** (Рацион.ТипКорма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Рацион.ТипКорма Set start)

                // *** End programmer edit section *** (Рацион.ТипКорма Set start)
                this.fТипКорма = value;
                // *** Start programmer edit section *** (Рацион.ТипКорма Set end)

                // *** End programmer edit section *** (Рацион.ТипКорма Set end)
            }
        }
        
        /// <summary>
        /// Рацион.
        /// </summary>
        // *** Start programmer edit section *** (Рацион.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (Рацион.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.EshheLegche.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (Рацион.Сотрудники Get start)

                // *** End programmer edit section *** (Рацион.Сотрудники Get start)
                IIS.EshheLegche.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (Рацион.Сотрудники Get end)

                // *** End programmer edit section *** (Рацион.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Рацион.Сотрудники Set start)

                // *** End programmer edit section *** (Рацион.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (Рацион.Сотрудники Set end)

                // *** End programmer edit section *** (Рацион.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РационE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РационE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РационE", typeof(IIS.EshheLegche.Рацион));
                }
            }
            
            /// <summary>
            /// "РационL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РационL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РационL", typeof(IIS.EshheLegche.Рацион));
                }
            }
        }
    }
}
