//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.EshheLegche
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Расписание.
    /// </summary>
    // *** Start programmer edit section *** (Расписание CustomAttributes)

    // *** End programmer edit section *** (Расписание CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РасписаниеE", new string[] {
            "ПервыйПрием as \'Первый прием\'",
            "ВторойПрием as \'Второй прием\'",
            "ТретийПрием as \'Третий прием\'",
            "Рацион as \'Рацион\'",
            "Рацион.НомерРациона as \'Номер рациона\'",
            "Должность as \'Должность\'",
            "Должность.Наименование as \'Наименование должности\'"}, Hidden=new string[] {
            "Должность.Наименование"})]
    [MasterViewDefineAttribute("РасписаниеE", "Рацион", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "СоставКорма")]
    [MasterViewDefineAttribute("РасписаниеE", "Должность", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [View("РасписаниеL", new string[] {
            "ПервыйПрием as \'Первый прием\'",
            "ВторойПрием as \'Второй прием\'",
            "ТретийПрием as \'Третий прием\'",
            "Должность.Наименование as \'Наименование должности\'",
            "Рацион.НомерРациона as \'Номер рациона\'"})]
    public class Расписание : ICSSoft.STORMNET.DataObject
    {
        
        private string fПервыйПрием;
        
        private string fВторойПрием;
        
        private string fТретийПрием;
        
        private IIS.EshheLegche.Рацион fРацион;
        
        private IIS.EshheLegche.Должность fДолжность;
        
        // *** Start programmer edit section *** (Расписание CustomMembers)

        // *** End programmer edit section *** (Расписание CustomMembers)

        
        /// <summary>
        /// ВторойПрием.
        /// </summary>
        // *** Start programmer edit section *** (Расписание.ВторойПрием CustomAttributes)

        // *** End programmer edit section *** (Расписание.ВторойПрием CustomAttributes)
        [StrLen(255)]
        public virtual string ВторойПрием
        {
            get
            {
                // *** Start programmer edit section *** (Расписание.ВторойПрием Get start)

                // *** End programmer edit section *** (Расписание.ВторойПрием Get start)
                string result = this.fВторойПрием;
                // *** Start programmer edit section *** (Расписание.ВторойПрием Get end)

                // *** End programmer edit section *** (Расписание.ВторойПрием Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Расписание.ВторойПрием Set start)

                // *** End programmer edit section *** (Расписание.ВторойПрием Set start)
                this.fВторойПрием = value;
                // *** Start programmer edit section *** (Расписание.ВторойПрием Set end)

                // *** End programmer edit section *** (Расписание.ВторойПрием Set end)
            }
        }
        
        /// <summary>
        /// ПервыйПрием.
        /// </summary>
        // *** Start programmer edit section *** (Расписание.ПервыйПрием CustomAttributes)

        // *** End programmer edit section *** (Расписание.ПервыйПрием CustomAttributes)
        [StrLen(255)]
        public virtual string ПервыйПрием
        {
            get
            {
                // *** Start programmer edit section *** (Расписание.ПервыйПрием Get start)

                // *** End programmer edit section *** (Расписание.ПервыйПрием Get start)
                string result = this.fПервыйПрием;
                // *** Start programmer edit section *** (Расписание.ПервыйПрием Get end)

                // *** End programmer edit section *** (Расписание.ПервыйПрием Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Расписание.ПервыйПрием Set start)

                // *** End programmer edit section *** (Расписание.ПервыйПрием Set start)
                this.fПервыйПрием = value;
                // *** Start programmer edit section *** (Расписание.ПервыйПрием Set end)

                // *** End programmer edit section *** (Расписание.ПервыйПрием Set end)
            }
        }
        
        /// <summary>
        /// ТретийПрием.
        /// </summary>
        // *** Start programmer edit section *** (Расписание.ТретийПрием CustomAttributes)

        // *** End programmer edit section *** (Расписание.ТретийПрием CustomAttributes)
        [StrLen(255)]
        public virtual string ТретийПрием
        {
            get
            {
                // *** Start programmer edit section *** (Расписание.ТретийПрием Get start)

                // *** End programmer edit section *** (Расписание.ТретийПрием Get start)
                string result = this.fТретийПрием;
                // *** Start programmer edit section *** (Расписание.ТретийПрием Get end)

                // *** End programmer edit section *** (Расписание.ТретийПрием Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Расписание.ТретийПрием Set start)

                // *** End programmer edit section *** (Расписание.ТретийПрием Set start)
                this.fТретийПрием = value;
                // *** Start programmer edit section *** (Расписание.ТретийПрием Set end)

                // *** End programmer edit section *** (Расписание.ТретийПрием Set end)
            }
        }
        
        /// <summary>
        /// Расписание.
        /// </summary>
        // *** Start programmer edit section *** (Расписание.Должность CustomAttributes)

        // *** End programmer edit section *** (Расписание.Должность CustomAttributes)
        [PropertyStorage(new string[] {
                "Должность"})]
        [NotNull()]
        public virtual IIS.EshheLegche.Должность Должность
        {
            get
            {
                // *** Start programmer edit section *** (Расписание.Должность Get start)

                // *** End programmer edit section *** (Расписание.Должность Get start)
                IIS.EshheLegche.Должность result = this.fДолжность;
                // *** Start programmer edit section *** (Расписание.Должность Get end)

                // *** End programmer edit section *** (Расписание.Должность Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Расписание.Должность Set start)

                // *** End programmer edit section *** (Расписание.Должность Set start)
                this.fДолжность = value;
                // *** Start programmer edit section *** (Расписание.Должность Set end)

                // *** End programmer edit section *** (Расписание.Должность Set end)
            }
        }
        
        /// <summary>
        /// Расписание.
        /// </summary>
        // *** Start programmer edit section *** (Расписание.Рацион CustomAttributes)

        // *** End programmer edit section *** (Расписание.Рацион CustomAttributes)
        [PropertyStorage(new string[] {
                "Рацион"})]
        [NotNull()]
        public virtual IIS.EshheLegche.Рацион Рацион
        {
            get
            {
                // *** Start programmer edit section *** (Расписание.Рацион Get start)

                // *** End programmer edit section *** (Расписание.Рацион Get start)
                IIS.EshheLegche.Рацион result = this.fРацион;
                // *** Start programmer edit section *** (Расписание.Рацион Get end)

                // *** End programmer edit section *** (Расписание.Рацион Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Расписание.Рацион Set start)

                // *** End programmer edit section *** (Расписание.Рацион Set start)
                this.fРацион = value;
                // *** Start programmer edit section *** (Расписание.Рацион Set end)

                // *** End programmer edit section *** (Расписание.Рацион Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РасписаниеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РасписаниеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РасписаниеE", typeof(IIS.EshheLegche.Расписание));
                }
            }
            
            /// <summary>
            /// "РасписаниеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РасписаниеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РасписаниеL", typeof(IIS.EshheLegche.Расписание));
                }
            }
        }
    }
}
