//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.EshheLegche
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Состав вольера.
    /// </summary>
    // *** Start programmer edit section *** (СоставВольера CustomAttributes)

    // *** End programmer edit section *** (СоставВольера CustomAttributes)
    [AutoAltered()]
    [Caption("Состав вольера")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СоставВольераE", new string[] {
            "Животные as \'Животные\'",
            "Животные.Кличка as \'Кличка\'",
            "Животные.Виды as \'Виды\'",
            "Животные.Виды.Наименование as \'Вид\'"}, Hidden=new string[] {
            "Животные.Кличка"})]
    [MasterViewDefineAttribute("СоставВольераE", "Животные", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Кличка")]
    public class СоставВольера : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.EshheLegche.Животные fЖивотные;
        
        private IIS.EshheLegche.Вольер fВольер;
        
        // *** Start programmer edit section *** (СоставВольера CustomMembers)

        // *** End programmer edit section *** (СоставВольера CustomMembers)

        
        /// <summary>
        /// Состав вольера.
        /// </summary>
        // *** Start programmer edit section *** (СоставВольера.Животные CustomAttributes)

        // *** End programmer edit section *** (СоставВольера.Животные CustomAttributes)
        [PropertyStorage(new string[] {
                "Животные"})]
        [NotNull()]
        public virtual IIS.EshheLegche.Животные Животные
        {
            get
            {
                // *** Start programmer edit section *** (СоставВольера.Животные Get start)

                // *** End programmer edit section *** (СоставВольера.Животные Get start)
                IIS.EshheLegche.Животные result = this.fЖивотные;
                // *** Start programmer edit section *** (СоставВольера.Животные Get end)

                // *** End programmer edit section *** (СоставВольера.Животные Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставВольера.Животные Set start)

                // *** End programmer edit section *** (СоставВольера.Животные Set start)
                this.fЖивотные = value;
                // *** Start programmer edit section *** (СоставВольера.Животные Set end)

                // *** End programmer edit section *** (СоставВольера.Животные Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.EshheLegche.Вольер.
        /// </summary>
        // *** Start programmer edit section *** (СоставВольера.Вольер CustomAttributes)

        // *** End programmer edit section *** (СоставВольера.Вольер CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Вольер"})]
        public virtual IIS.EshheLegche.Вольер Вольер
        {
            get
            {
                // *** Start programmer edit section *** (СоставВольера.Вольер Get start)

                // *** End programmer edit section *** (СоставВольера.Вольер Get start)
                IIS.EshheLegche.Вольер result = this.fВольер;
                // *** Start programmer edit section *** (СоставВольера.Вольер Get end)

                // *** End programmer edit section *** (СоставВольера.Вольер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставВольера.Вольер Set start)

                // *** End programmer edit section *** (СоставВольера.Вольер Set start)
                this.fВольер = value;
                // *** Start programmer edit section *** (СоставВольера.Вольер Set end)

                // *** End programmer edit section *** (СоставВольера.Вольер Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СоставВольераE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СоставВольераE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СоставВольераE", typeof(IIS.EshheLegche.СоставВольера));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of СоставВольера.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfСоставВольера CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfСоставВольера CustomAttributes)
    public class DetailArrayOfСоставВольера : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.EshheLegche.DetailArrayOfСоставВольера members)

        // *** End programmer edit section *** (IIS.EshheLegche.DetailArrayOfСоставВольера members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type СоставВольера by index.
        /// </summary>
        /// <summary>
        /// Adds object with type СоставВольера.
        /// </summary>
        public DetailArrayOfСоставВольера(IIS.EshheLegche.Вольер fВольер) : 
                base(typeof(СоставВольера), ((ICSSoft.STORMNET.DataObject)(fВольер)))
        {
        }
        
        public IIS.EshheLegche.СоставВольера this[int index]
        {
            get
            {
                return ((IIS.EshheLegche.СоставВольера)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.EshheLegche.СоставВольера dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
