//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.EshheLegche
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тип корма.
    /// </summary>
    // *** Start programmer edit section *** (ТипКорма CustomAttributes)

    // *** End programmer edit section *** (ТипКорма CustomAttributes)
    public enum ТипКорма
    {
        
        // *** Start programmer edit section *** (ТипКорма.Мокрый CustomAttributes)

        // *** End programmer edit section *** (ТипКорма.Мокрый CustomAttributes)
        [Caption("Мокрый")]
        Мокрый,
        
        // *** Start programmer edit section *** (ТипКорма.Сухой CustomAttributes)

        // *** End programmer edit section *** (ТипКорма.Сухой CustomAttributes)
        [Caption("Сухой")]
        Сухой,
        
        // *** Start programmer edit section *** (ТипКорма.фруктыИОвощи CustomAttributes)

        // *** End programmer edit section *** (ТипКорма.фруктыИОвощи CustomAttributes)
        [Caption("Фрукты и овощи")]
        фруктыИОвощи,
        
        // *** Start programmer edit section *** (ТипКорма.СеноИТрава CustomAttributes)

        // *** End programmer edit section *** (ТипКорма.СеноИТрава CustomAttributes)
        [Caption("Сено и трава")]
        СеноИТрава,
        
        // *** Start programmer edit section *** (ТипКорма.ЗерноКрупы CustomAttributes)

        // *** End programmer edit section *** (ТипКорма.ЗерноКрупы CustomAttributes)
        [Caption("Зерно крупы")]
        ЗерноКрупы,
        
        // *** Start programmer edit section *** (ТипКорма.МясоИлиРыба CustomAttributes)

        // *** End programmer edit section *** (ТипКорма.МясоИлиРыба CustomAttributes)
        [Caption("Мясо или рыба")]
        МясоИлиРыба,
    }
}
