//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.EshheLegche
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тип вольера.
    /// </summary>
    // *** Start programmer edit section *** (ТипВольера CustomAttributes)

    // *** End programmer edit section *** (ТипВольера CustomAttributes)
    public enum ТипВольера
    {
        
        // *** Start programmer edit section *** (ТипВольера.крупных CustomAttributes)

        // *** End programmer edit section *** (ТипВольера.крупных CustomAttributes)
        крупных,
        
        // *** Start programmer edit section *** (ТипВольера.животных CustomAttributes)

        // *** End programmer edit section *** (ТипВольера.животных CustomAttributes)
        животных,
        
        // *** Start programmer edit section *** (ТипВольера.Для CustomAttributes)

        // *** End programmer edit section *** (ТипВольера.Для CustomAttributes)
        Для,
        
        // *** Start programmer edit section *** (ТипВольера.птиц CustomAttributes)

        // *** End programmer edit section *** (ТипВольера.птиц CustomAttributes)
        птиц,
        
        // *** Start programmer edit section *** (ТипВольера.Аквариум CustomAttributes)

        // *** End programmer edit section *** (ТипВольера.Аквариум CustomAttributes)
        Аквариум,
        
        // *** Start programmer edit section *** (ТипВольера.Терариум CustomAttributes)

        // *** End programmer edit section *** (ТипВольера.Терариум CustomAttributes)
        Терариум,
        
        // *** Start programmer edit section *** (ТипВольера.Экзотический CustomAttributes)

        // *** End programmer edit section *** (ТипВольера.Экзотический CustomAttributes)
        Экзотический,
    }
}
