//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.EshheLegche
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тип корма.
    /// </summary>
    // *** Start programmer edit section *** (ТипКорма CustomAttributes)

    // *** End programmer edit section *** (ТипКорма CustomAttributes)
    public enum ТипКорма
    {
        
        // *** Start programmer edit section *** (ТипКорма.Сухой CustomAttributes)

        // *** End programmer edit section *** (ТипКорма.Сухой CustomAttributes)
        Сухой,
        
        // *** Start programmer edit section *** (ТипКорма.Мокрый CustomAttributes)

        // *** End programmer edit section *** (ТипКорма.Мокрый CustomAttributes)
        Мокрый,
        
        // *** Start programmer edit section *** (ТипКорма.фрукты CustomAttributes)

        // *** End programmer edit section *** (ТипКорма.фрукты CustomAttributes)
        фрукты,
        
        // *** Start programmer edit section *** (ТипКорма.овощи CustomAttributes)

        // *** End programmer edit section *** (ТипКорма.овощи CustomAttributes)
        овощи,
        
        // *** Start programmer edit section *** (ТипКорма.Сено CustomAttributes)

        // *** End programmer edit section *** (ТипКорма.Сено CustomAttributes)
        Сено,
        
        // *** Start programmer edit section *** (ТипКорма.трава CustomAttributes)

        // *** End programmer edit section *** (ТипКорма.трава CustomAttributes)
        трава,
        
        // *** Start programmer edit section *** (ТипКорма.Зерно CustomAttributes)

        // *** End programmer edit section *** (ТипКорма.Зерно CustomAttributes)
        Зерно,
        
        // *** Start programmer edit section *** (ТипКорма.и CustomAttributes)

        // *** End programmer edit section *** (ТипКорма.и CustomAttributes)
        и,
        
        // *** Start programmer edit section *** (ТипКорма.крупы CustomAttributes)

        // *** End programmer edit section *** (ТипКорма.крупы CustomAttributes)
        крупы,
        
        // *** Start programmer edit section *** (ТипКорма.Мясо CustomAttributes)

        // *** End programmer edit section *** (ТипКорма.Мясо CustomAttributes)
        Мясо,
        
        // *** Start programmer edit section *** (ТипКорма.или CustomAttributes)

        // *** End programmer edit section *** (ТипКорма.или CustomAttributes)
        или,
        
        // *** Start programmer edit section *** (ТипКорма.рыба CustomAttributes)

        // *** End programmer edit section *** (ТипКорма.рыба CustomAttributes)
        рыба,
    }
}
